language: node_js
node_js:
  - '0.10.26'
before_script:
  - 'npm install -g bower grunt-cli'
notifications:
  email:
    recipients:
      - todd@sparkfun.com
    on_success: change
    on_failure: change
